# Netlify Build and Redirect Configuration
[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://portfolio-backend-bhuvi.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
